steps:
  - name: 'curlimages/curl'
    entrypoint: 'curl'
    args:
      - '-X'
      - 'POST'
      - 'https://api.bugster.app/webhooks/integrations/custom'
      - '-H'
      - 'Content-Type: application/json'
      - '-H'
      - 'X-API-KEY: ${_BUGSTER_API_KEY}'
      - '--data'
      - |
        {
          "deployment_state": "success",
          "project_id": "${_PROJECT_ID}",
          "organization_id": "${_ORG_ID}",
          "branch": "${_BRANCH_NAME}",
          "environment_url": "${_DEPLOYMENT_URL}",
          "environment": "production"
        }
options:
    logging: CLOUD_LOGGING_ONLY